name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      foo: 
        description: "bar|baz"
        type: choice
        options:
          - "bar"
          - "baz"
        default: "baz"
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: List files in repository
        run: |
          echo "the repository ${{ github.repository }} contains the following files:"
          tree
  MySecondJob:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: "echo foo: ${{ inputs.foo }}"
